http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  recommendationAPI:
    host: localhost
    paths: '/api/news/*'
  authenticationAPI:
    host: localhost
    paths: '/api/auth/account/*'
serviceEndpoints:
  recommendationService:
    url: 'https://localhost:31001'
  authenticationService:
    url: 'https://localhost:31002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  recommendationPipeline:
    apiEndpoints:
      - recommendationAPI
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: recommendationService
              changeOrigin: true
  authenticationPipeline:
    apiEndpoints:
      - authenticationAPI
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authenticationService
              changeOrigin: true
