USE AUTHENTICATION_SERVICE;
create database AUTHENTICATION_SERVICE;

CREATE TABLE USERS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(255) NOT NULL,
	email NVARCHAR(255) NOT NULL,
    password NVARCHAR(255) NOT NULL
);

--DROP TABLE USERS;

DELETE FROM USERS 