
CREATE DATABASE NEWS_SERVICE;
use NEWS_SERVICE
  
CREATE TABLE NEWS (
    ID INT PRIMARY KEY IDENTITY,
    TITLE TEXT NOT NULL,
    PARAGRAPH TEXT NOT NULL,
    ALT TEXT NOT NULL,
    LINK NVARCHAR(255) NOT NULL,
    IMAGE NVARCHAR(255) NOT NULL,
    DATE NVARCHAR(255) NOT NULL,
    TOPIC_NAME nvarchar(255) not null
);

DELETE FROM NEWS;

drop table NEWS; 

SELECT * FROM NEWS; 
 