
CREATE DATABASE NEWS_SERVICE;
use NEWS_SERVICE

create table TOPICS (
    ID        int primary key identity (1,1),
    TOPIC_NAME nvarchar(255) not null,
)

CREATE TABLE NEWS (
    ID INT PRIMARY KEY IDENTITY,
    TITLE TEXT NOT NULL,
    PARAGRAPH TEXT NOT NULL,
    ALT TEXT NOT NULL,
    LINK NVARCHAR(255) NOT NULL,
    IMAGE NVARCHAR(255) NOT NULL,
    DATE NVARCHAR(255) NOT NULL,
    TOPIC_ID INT,
    FOREIGN KEY (TOPIC_ID) REFERENCES TOPICS(ID)
);

DELETE FROM NEWS;

drop table NEWS;
drop table TOPICS;

SELECT * FROM NEWS;