CREATE DATABASE RECOMMENDATION_SERVICE;

CREATE TABLE NEWS
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    Heading NVARCHAR(255) NOT NULL,
    Paragraph NVARCHAR(MAX) NOT NULL,
    Date NVARCHAR(255) NOT NULL
);



DELETE FROM NEWS;

SELECT * FROM NEWS;