
CREATE DATABASE RECOMMENDATION_SERVICE;

CREATE TABLE NEWS (
    ID INT PRIMARY KEY IDENTITY,
    Heading NVARCHAR(255) NOT NULL,
    Paragraph NVARCHAR(MAX) NOT NULL,
    Date NVARCHAR(255) NOT NULL,
    TopicId INT,
    FOREIGN KEY (TopicId) REFERENCES TOPICS(ID)
);


CREATE TAble topics
(
    ID        INT PRIMARY KEY IDENTITY (1,1),
    TopicName NVARCHAR(255) NOT NULL,
)

DELETE FROM NEWS;

drop table news;

SELECT * FROM NEWS;